### ISSUE TITLE
RangeError: Invalid count value on CI

### ISSUE THREAD

**Issue by ls-joris-desmedt** [apideck-libraries/portman#126]
Hey,

First of all, thanks for this library. We just started using this to help us automate some steps in our `API-design-first` journey at our company and it is working great.

However, we encountered some issues when running portman the first time in our CI environment (we are using CircleCI).
This issue was only encountered in the CI environment itself.

When running

```
portman --cliOptionsFile ./portman-cli-config.json -b http://localhost:8089
```

We got the following error in CircleCI:

```
RangeError: Invalid count value
    at String.repeat (<anonymous>)
    at new Portman (/usr/local/lib/node_modules/@apideck/portman/dist/Portman.js:21:32)
    at /usr/local/lib/node_modules/@apideck/portman/dist/index.js:162:27
    at step (/usr/local/lib/node_modules/@apideck/portman/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/@apideck/portman/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/usr/local/lib/node_modules/@apideck/portman/node_modules/tslib/tslib.js:114:62)
```

After checking the code I saw that the following [line](https://github.com/apideck-libraries/portman/blob/main/src/Portman.ts#L47) was causing this error:

```
this.consoleLine = '='.repeat(process.stdout.columns - 80)
```

On some CI setups, the terminal width will be 0 (eg: CircleCI) meaning that `process.stdout.columns` will be `0` returning the error above.
This error will also happen on narrow terminals containing less then 80 columns.

A quick workaround is possible by adding the following line before the portman command:

```
stty rows 64 cols 204
portman --cliOptionsFile ./portman-cli-config.json -b http://localhost:8089
```

This will set the number of columns in the terminal before executing portman. You just have to make sure that the number of columns is at least 80.

To harden the code, you can maybe add a check when creating that line in the code:

```
this.consoleLine = '='.repeat(Math.max(process.stdout.columns, 80) - 80)
```

This way the library will still work on CI and smaller terminals.

**Comment by thim81** [comment]
Thanks @ls-joris-desmedt for reporting the error. 

We were not aware of the column issue and that some CI had no or a very small column length. 

We will improve the piece of code that handles the columns output, in one of the next releases. 

Are you blocked with this current issue?

**Comment by ls-joris-desmedt** [comment]
@thim81 take your time, this is not an urgent issue as the workaround is pretty simple (see my previous comment).

Just wanted to add it here to help other people who would experience the same.

**Comment by thim81** [comment]
@ls-joris-desmedt We just pushed a PR to fix the behaviour, which mostlikely land in the next release.

We had to tackle it a bit differently since the Math.max() could potentially return a NaN, because it is possible that the process.stdout.columns would return undefined. 

Taken from [Math.max()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/max)
> If at least one of arguments cannot be converted to a number, the result is NaN
