### ISSUE TITLE
Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by VDRobert** [apideck-libraries/portman#135]
When issuing the following command on a valid swagger.json I get the following exception. P.s I am using version 1.1.3

Command  `portman  -l .\swagger.json --trace-warnings -o postman.json`

`(node:33580) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined
    at Object.orderCollectionRequests (C:\Users\me\AppData\Roaming\npm\node_modules\@apideck\portman\dist\application\globals\orderCollectionRequests.js:9:14)
    at CollectionWriter.execute (C:\Users\me\AppData\Roaming\npm\node_modules\@apideck\portman\dist\application\CollectionWriter.js:28:29)
    at Portman.<anonymous> (C:\Users\me\AppData\Roaming\npm\node_modules\@apideck\portman\dist\Portman.js:281:34)
    at step (C:\Users\me\AppData\Roaming\npm\node_modules\@apideck\portman\node_modules\tslib\tslib.js:143:27)
    at Object.next (C:\Users\me\AppData\Roaming\npm\node_modules\@apideck\portman\node_modules\tslib\tslib.js:124:57)
    at C:\Users\me\AppData\Roaming\npm\node_modules\@apideck\portman\node_modules\tslib\tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Users\me\AppData\Roaming\npm\node_modules\@apideck\portman\node_modules\tslib\tslib.js:113:16)
    at Portman.runPortmanOverrides (C:\Users\me\AppData\Roaming\npm\node_modules\@apideck\portman\dist\Portman.js:276:24)
    at Portman.<anonymous> (C:\Users\me\AppData\Roaming\npm\node_modules\@apideck\portman\dist\Portman.js:240:45)
    at step (C:\Users\me\AppData\Roaming\npm\node_modules\@apideck\portman\node_modules\tslib\tslib.js:143:27)
    at Object.next (C:\Users\me\AppData\Roaming\npm\node_modules\@apideck\portman\node_modules\tslib\tslib.js:124:57)
    at C:\Users\me\AppData\Roaming\npm\node_modules\@apideck\portman\node_modules\tslib\tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Users\me\AppData\Roaming\npm\node_modules\@apideck\portman\node_modules\tslib\tslib.js:113:16)
    at Portman.convertToPostmanCollection (C:\Users\me\AppData\Roaming\npm\node_modules\@apideck\portman\dist\Portman.js:211:24)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:33580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process 
on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:33580) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by VDRobert** [comment]
Is version 1.8.0 also released as a npm package? I cant seem to update to it using 
`npm install -g portman@1.8.0`

**Comment by thim81** [comment]
Hi @VDRobert 

Version 1.8.0 should be available as NPM package: https://www.npmjs.com/package/@apideck/portman

You can also experiment with it using NPX

`npx @apideck/portman -l your-openapi-file.yaml`

**Comment by VDRobert** [comment]
Using npx with 1.8.0 solved it. Thank you!
