### ISSUE TITLE
RangeError: Maximum call stack size exceeded when using recursive schema's

### ISSUE THREAD

**Issue by ls-liesbeth-dekeyzer** [apideck-libraries/portman#178]
When generating our postman collection for our open api spec we get an exception. 
Our schema's do have some recursive calls, for example:

![Screenshot 2021-11-30 at 12 02 11](https://user-images.githubusercontent.com/43766866/144035668-0c7e1be1-d17e-4315-9042-dc93597c9c54.png)

This is a part of our open api spec file
```
 "menuEntryGroups": {
                      "items": {
                        "oneOf": [
                          {
                            "title": "menuGroupEntry",
                            "properties": {
                              "name": {
                                "example": "drinks",
                                "type": "string"
                              },
                              "color": {
                                "example": "blue",
                                "type": "string"
                              },
                              "menuEntry": {
                                "$ref": "#/components/schemas/menuEntry"
                              },
                              "type": {
                                "enum": ["group", "menuItem", "menuDeal"],
                                "example": "group",
                                "type": "string"
                              }
                            },
                            "type": "object"
                          }
```

Is this a bug or could I fix this by adding some extra options?
```

error:  RangeError: Maximum call stack size exceeded
    at crawl (/Users/liesbeth.de.keyzer/Documents/workspace/api-platform/node_modules/@apidevtools/json-schema-ref-parser/lib/bundle.js:39:16)
    at crawl (/Users/liesbeth.de.keyzer/Documents/workspace/api-platform/node_modules/@apidevtools/json-schema-ref-parser/lib/bundle.js:77:11)
    at crawl (/Users/liesbeth.de.keyzer/Documents/workspace/api-platform/node_modules/@apidevtools/json-schema-ref-parser/lib/bundle.js:77:11)
    at crawl (/Users/liesbeth.de.keyzer/Documents/workspace/api-platform/node_modules/@apidevtools/json-schema-ref-parser/lib/bundle.js:77:11)
    at crawl (/Users/liesbeth.de.keyzer/Documents/workspace/api-platform/node_modules/@apidevtools/json-schema-ref-parser/lib/bundle.js:77:11)
    at crawl (/Users/liesbeth.de.keyzer/Documents/workspace/api-platform/node_modules/@apidevtools/json-schema-ref-parser/lib/bundle.js:77:11)
    at crawl (/Users/liesbeth.de.keyzer/Documents/workspace/api-platform/node_modules/@apidevtools/json-schema-ref-parser/lib/bundle.js:77:11)
    at crawl (/Users/liesbeth.de.keyzer/Documents/workspace/api-platform/node_modules/@apidevtools/json-schema-ref-parser/lib/bundle.js:77:11)
    at crawl (/Users/liesbeth.de.keyzer/Documents/workspace/api-platform/node_modules/@apidevtools/json-schema-ref-parser/lib/bundle.js:77:11)
    at crawl (/Users/liesbeth.de.keyzer/Documents/workspace/api-platform/node_modules/@apidevtools/json-schema-ref-parser/lib/bundle.js:77:11)
    at crawl (/Users/liesbeth.de.keyzer/Documents/workspace/api-platform/node_modules/@apidevtools/json-schema-ref-parser/lib/bundle.js:77:11)
    at crawl (/Users/liesbeth.de.keyzer/Documents/workspace/api-platform/node_modules/@apidevtools/json-schema-ref-parser/lib/bundle.js:77:11)
    at crawl (/Users/liesbeth.de.keyzer/Documents/workspace/api-platform/node_modules/@apidevtools/json-schema-ref-parser/lib/bundle.js:77:11)
    at crawl (/Users/liesbeth.de.keyzer/Documents/workspace/api-platform/node_modules/@apidevtools/json-schema-ref-parser/lib/bundle.js:77:11)
    at crawl (/Users/liesbeth.de.keyzer/Documents/workspace/api-platform/node_modules/@apidevtools/json-schema-ref-parser/lib/bundle.js:77:11)
    at crawl (/Users/liesbeth.de.keyzer/Documents/workspace/api-platform/node_modules/@apidevtools/json-schema-ref-parser/lib/bundle.js:77:11)
/Users/liesbeth.de.keyzer/Documents/workspace/api-platform/node_modules/@apideck/portman/dist/Portman.js:217
                                throw new Error("Parsing " + openApiSpec + " failed.");
                                      ^

Error: Parsing ./tmp/converted/spec.yml failed.
    at /Users/liesbeth.de.keyzer/Documents/workspace/api-platform/node_modules/@apideck/portman/dist/Portman.js:217:39
error Command failed with exit code 1.
```

**Comment by thim81** [comment]
@ls-liesbeth-dekeyzer Thanks for sharing your issue.

Is the OpenAPI file publicly available? That way we can try to reproduce it.

**Comment by ls-liesbeth-dekeyzer** [comment]
Its not yet publicly available. I added here (I couldnt add it as a openapi.json file)

[openapi.txt](https://github.com/apideck-libraries/portman/files/7626048/openapi.txt)

**Comment by nicklloyd** [comment]
Thanks for sharing @ls-liesbeth-dekeyzer  - will try to repro and see if we can get this sorted

**Comment by nicklloyd** [comment]
Hi @ls-liesbeth-dekeyzer - might have a fix, but is it possible that the postman collection hosted here: https://developers.lightspeedhq.com/ecom/introduction/postman/ is from a different spec?

Just comparing our current output from Portman...

**Comment by ls-liesbeth-dekeyzer** [comment]
> Ah sorry have just seen: "Lightspeed Restaurant K Series API" vs "Lightspeed eCom V2" in the collections

Yeah ecom is a different product inside lightspeed. So not the same api spec

**Comment by nicklloyd** [comment]
Hey @ls-liesbeth-dekeyzer, just to inform you there is an impending release that will allow you to `ignoreCircularRefs`. 

Ideally the spec should not contain any circular references, but this will at least maintain the rest of Portman's value. 

Do note that this means for requests with a response schema containing circular refs, schema validation _will not_ be included in your test suite.

Let you know when the release is published, but would guess within the next couple hours.

**Comment by nicklloyd** [comment]
v1.12.0 has been released. Please give it a spin and let us know if this suits your case.

Your options are described here: https://github.com/apideck-libraries/portman/blob/main/docs/ERRORS.md.

I'll closed this issue for now, but please reopen or create a new one if needed.
