### ISSUE TITLE
Cannot read property 'url' of undefined

### ISSUE THREAD

**Issue by thim81** [apideck-libraries/portman#2]
When using the postman configuration:

```
{
  "folderStrategy": "Paths",
  "requestParametersResolution": "Example",
  "exampleParametersResolution": "Example"
}

```
The following error occurs:

```
TypeError: Cannot read property 'url' of undefined
    at /lib/transforms/overridePathParams.js:12:34

```

**Comment by nicklloyd** [comment]
This one trickles down... think it's the way we're trying to access operations/requests... 

```(node:29357) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'url' of undefined
    at /Users/nick/Development/apideck/unify-portman/node_modules/@apideck/portman/dist/lib/transforms/orderCollectionRequests.js:12:51```
