### ISSUE TITLE
Upload to postman fails for empty postman workspace

### ISSUE THREAD

**Issue by KellMar** [apideck-libraries/portman#201]
Hey,

I wanted to clean my postman workspace today and regenerate all collections with portman, but unfortunately it failed with error below.

This in the PostmanRepo.js line 165 fixed it locally for me. Now, since one collection is in there the upload works again.

`        if (!this.cache.workspace.collections) {
            return undefined;
        }`

`  ✔ Conversion successful
(node:15097) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'filter' of undefined
    at PostmanRepo.findWorkspaceCollectionByName (/Users/markusk/.npm/_npx/94d4c499b73a63ed/node_modules/@apideck/portman/dist/services/PostmanRepo.js:167:56)
    at PostmanSyncService.existsInWorkspace (/Users/markusk/.npm/_npx/94d4c499b73a63ed/node_modules/@apideck/portman/dist/services/PostmanSyncService.js:130:32)
    at PostmanSyncService.shouldUpdate (/Users/markusk/.npm/_npx/94d4c499b73a63ed/node_modules/@apideck/portman/dist/services/PostmanSyncService.js:118:25)
    at PostmanSyncService.<anonymous> (/Users/markusk/.npm/_npx/94d4c499b73a63ed/node_modules/@apideck/portman/dist/services/PostmanSyncService.js:80:51)
    at step (/Users/markusk/.npm/_npx/94d4c499b73a63ed/node_modules/tslib/tslib.js:143:27)
    at Object.next (/Users/markusk/.npm/_npx/94d4c499b73a63ed/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/Users/markusk/.npm/_npx/94d4c499b73a63ed/node_modules/tslib/tslib.js:114:62)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15097) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15097) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

BTW thank you! I really enjoy portman!

**Comment by thim81** [comment]
hi @KellMar 

To not overload the Postman API when syncing the generated Postman collections, Portman keeps a local cache of the workspaces and collections in the workspace.

It might be that there is something off in the cache which causes the error to occur.

Could you try to find the file `.portman.cache.json` (usually in the "tmp" folder), and remove that file?

Portman will try to rebuild the cache on the next sync towards Postman.

**Comment by KellMar** [comment]
Hey @thim81,

thanks for the fast reply! I'm running portman in an azure pipeline from the cli.

I always thought the cache will be deleted there. But I'll look into it tomorrow.

**Comment by thim81** [comment]
Could you share which cli options you are using or the --cliOptionsFile file? 

That way we can try to reproduce the behaviour.

**Comment by KellMar** [comment]
Sure, sorry for not providing this in advance.

cliOptionsFile:
`{
  "portmanConfigFile": "pipeline/portman/portman-config.json",
  "includeTests": true,
  "syncPostman": true,
  "postmanWorkspaceName": "some-workspace-name",
  "runNewman": false
}
`
And it is running in the pipeline with:

`npx @apideck/portman --cliOptionsFile pipeline/portman/portman-apim-cli-options.json -l some-yaml-file-path.yaml
`

**Comment by thim81** [comment]
@KellMar 

The configuration is helpful for us to understand the setup.
To be able to leverage the `syncPostman` Portman will look for ENV variables with `POSTMAN_API_KEY=[replace with Postman api key]`. Is this setup in your pipeline?
(just asking to rule out if missing config is the cause)

**Comment by KellMar** [comment]
Yes it is set to the ENV in the pipeline. 

The portman postman update works fine with my pipeline.

It just did not work, when I deleted all collections and wanted to regenerate the whole workspace.

It was fixed by creating a new collection and run the pipeline again.

**Comment by thim81** [comment]
Based on your explanation and the way to overcome it, it seems that Portman fails on a missing variable. 

I ll mark this as a bug, and we will try to patch in one of the next releases.

**Comment by nicklloyd** [comment]
Hi @KellMar - thanks for reporting. This has been resolved in 1.12.2. 

Let us know if you come across anything else!
