### ISSUE TITLE
orderOfOperations fails when used with `--postmanConfigFile`

### ISSUE THREAD

**Issue by tillig** [apideck-libraries/portman#467]
Given a `portman-config.json` where there is a `globals.orderOfOperations` specified for operations. If you build the tests like this...

`npx portman -l schema.json -b http://localhost -o postman-collection.json -c portman-config.json`

Things build just fine and `orderOfOperations` works as expected.

However, add a JSON file `postman-config.json` to the filesystem and add an empty JSON object:

```json
{
}
```

It doesn't matter if it's empty or if it has some valid Postman config. It may be like this, too:

```json
{
  "folderStrategy": "Paths",
  "requestParametersResolution": "Example"
}
```

Now build the tests but use the Postman config:

`npx portman -l schema.json -b http://localhost -o postman-collection.json -c portman-config.json --postmanConfigFile postman-config.json`

In this case, the tests will fail to generate with an error like this:

```text
/Users/tillig/my-spec/node_modules/@apideck/portman/dist/application/globals/orderCollectionRequests.js:17
                var postmanPath = request.request.url.path.join('/');
                                                  ^

TypeError: Cannot read properties of undefined (reading 'url')
    at /Users/tillig/my-spec/node_modules/@apideck/portman/dist/application/globals/orderCollectionRequests.js:17:51
    at Array.map (<anonymous>)
    at /Users/tillig/my-spec/node_modules/@apideck/portman/dist/application/globals/orderCollectionRequests.js:16:27
    at Array.map (<anonymous>)
    at Object.orderCollectionRequests (/Users/tillig/my-spec/node_modules/@apideck/portman/dist/application/globals/orderCollectionRequests.js:11:14)
    at CollectionWriter.execute (/Users/tillig/my-spec/node_modules/@apideck/portman/dist/application/CollectionWriter.js:31:29)
    at Portman.<anonymous> (/Users/tillig/my-spec/node_modules/@apideck/portman/dist/Portman.js:337:34)
    at step (/Users/tillig/my-spec/node_modules/tslib/tslib.js:144:27)
    at Object.next (/Users/tillig/my-spec/node_modules/tslib/tslib.js:125:57)
    at /Users/tillig/my-spec/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/tillig/my-spec/node_modules/tslib/tslib.js:114:16)
    at Portman.runPortmanOverrides (/Users/tillig/my-spec/node_modules/@apideck/portman/dist/Portman.js:332:24)
    at Portman.<anonymous> (/Users/tillig/my-spec/node_modules/@apideck/portman/dist/Portman.js:288:45)
    at step (/Users/tillig/my-spec/node_modules/tslib/tslib.js:144:27)
    at Object.next (/Users/tillig/my-spec/node_modules/tslib/tslib.js:125:57)
```

Somehow, the use of the `--postmanConfigFile` option stops that `url` property from getting populated and ordering fails.

**Comment by thim81** [comment]
hi @tillig 

We have merged a PR that should handle the error.

**Comment by thim81** [comment]
hi @tillig 

We just released Portman v1.22.0, which handles the error.
Could you keep us posted if it solved your issue?

**Comment by tillig** [comment]
Will do. I'm OOF for a bit, will check when I'm back in. Thanks!

**Comment by tillig** [comment]
Verified - this works and we no longer see the error. Thanks for the patch! Much appreciated!
