### ISSUE TITLE
Wrong portman variation tests while using OpenAPI keyword as schema property name

### ISSUE THREAD

**Issue by challakamal** [apideck-libraries/portman#513]
I have an issue with portman variation test while using OpenAPI keyword as schema property name, in this case '**maxLength**'

```
"maxLength": {
    "default": 1024,
    "description": "Maximum length of the field value.",
    "example": 10,
    "type": "number"
  }
```

The following command creating one variation test `post-example-fields[400 - Validation][maximum length properties]` with proper payload  but expecting 400 bad request.
`portman -l schema.json -c portman-config.json`

**full schema.json**
```{
  "components": {
    "responses": {
      "400badRequest": {
        "description": "The request could not be processed by the server. This may be due to malformed syntax or a semantic error (for example, a value in the request failed validation for length, range, and so on). Check your parameters and retry."
      },
      "401unauthorized": {
        "description": "The request is missing valid authentication credentials."
      }
    },
    "schemas": {
      "field": {
        "description": "Base information about a field.",
        "properties": {
          "dataType": {
            "description": "Data type of the field for validation.",
            "enum": [
              "boolean",
              "date",
              "integer",
              "number",
              "string"
            ],
            "example": "string",
            "type": "string"
          },
          "maxLength": {
            "default": 1024,
            "description": "Maximum length of the field value.",
            "example": 10,
            "type": "number"
          },
          "name": {
            "description": "Name of the field.",
            "example": "employeeNumber",
            "maxLength": 1024,
            "type": "string"
          }
        },
        "required": [
          "name",
          "dataType"
        ],
        "type": "object"
      }
    }
  },
  "info": {
    "description": "Routes for fields.",
    "title": "Fields",
    "version": "0.0.1"
  },
  "openapi": "3.0.3",
  "paths": {
    "/example/fields": {
      "post": {
        "description": "Creates a field.",
        "operationId": "post-example-fields",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/field"
              }
            }
          }
        },
        "responses": {
          "201": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/field"
                }
              }
            },
            "description": "Successfully created the field."
          },
          "400": {
            "$ref": "#/components/responses/400badRequest"
          },
          "401": {
            "$ref": "#/components/responses/401unauthorized"
          }
        }
      }
    }
  }
}
```

**portman-config.json**
```
{
  "globals": {
    "stripResponseExamples": true
  },
  "overwrites": [
  ],
  "tests": {
    "contractTests": [
      {
        "contentType": {
          "enabled": true
        },
        "headersPresent": {
          "enabled": true
        },
        "jsonBody": {
          "enabled": true
        },
        "openApiOperation": "*::/*",
        "schemaValidation": {
          "enabled": true
        },
        "statusSuccess": {
          "enabled": true
        }
      }
    ],
    "variationTests": [
      {
        "openApiOperation": "*::/*",
        "openApiResponse": "400",
        "variations": [
          {
            "fuzzing": [
              {
                "requestBody": [
                  {
                    "maxLengthFields": {
                      "enabled": true
                    },
                    "maximumNumberFields": {
                      "enabled": true
                    },
                    "minLengthFields": {
                      "enabled": true
                    },
                    "minimumNumberFields": {
                      "enabled": true
                    },
                    "requiredFields": {
                      "enabled": true
                    }
                  }
                ],
                "requestHeaders": [
                  {
                    "maxLengthFields": {
                      "enabled": true
                    },
                    "maximumNumberFields": {
                      "enabled": true
                    },
                    "minLengthFields": {
                      "enabled": true
                    },
                    "minimumNumberFields": {
                      "enabled": true
                    },
                    "requiredFields": {
                      "enabled": true
                    }
                  }
                ],
                "requestQueryParams": [
                  {
                    "maxLengthFields": {
                      "enabled": true
                    },
                    "maximumNumberFields": {
                      "enabled": true
                    },
                    "minLengthFields": {
                      "enabled": true
                    },
                    "minimumNumberFields": {
                      "enabled": true
                    },
                    "requiredFields": {
                      "enabled": true
                    }
                  }
                ]
              }
            ],
            "name": "400 - Validation",
            "tests": {
              "contractTests": [
                {
                  "contentType": {
                    "enabled": true
                  },
                  "headersPresent": {
                    "enabled": true
                  },
                  "jsonBody": {
                    "enabled": true
                  },
                  "schemaValidation": {
                    "enabled": true
                  },
                  "statusCode": {
                    "enabled": true
                  }
                }
              ]
            }
          }
        ]
      }
    ]
  },
  "version": 1
}
```

**Comment by tillig** [comment]
We just ran into a similar issue where we have a property `required` on one of our objects.

**Comment by tillig** [comment]
Doing some research on where/how to fix this. For a property named `required` I see the exception during test generation looks like this:

```text
/Users/tillig/specification/node_modules/@apideck/portman/dist/application/Fuzzer.js:497
                var requiredFuzz = node.required.map(function (req) { return "" + requiredPath + req; });
                                                 ^

TypeError: node.required.map is not a function
    at Object.<anonymous> (/Users/tillig/specification/node_modules/@apideck/portman/dist/application/Fuzzer.js:497:50)
    at walker (/Users/tillig/specification/node_modules/traverse/index.js:150:16)
    at /Users/tillig/specification/node_modules/traverse/index.js:171:17
    at Array.forEach (<anonymous>)
    at forEach (/Users/tillig/specification/node_modules/traverse/index.js:19:30)
    at walker (/Users/tillig/specification/node_modules/traverse/index.js:166:4)
    at /Users/tillig/specification/node_modules/traverse/index.js:171:17
    at Array.forEach (<anonymous>)
    at forEach (/Users/tillig/specification/node_modules/traverse/index.js:19:30)
    at walker (/Users/tillig/specification/node_modules/traverse/index.js:166:4)
    at /Users/tillig/specification/node_modules/traverse/index.js:171:17
    at Array.forEach (<anonymous>)
    at forEach (/Users/tillig/specification/node_modules/traverse/index.js:19:30)
    at walker (/Users/tillig/specification/node_modules/traverse/index.js:166:4)
    at /Users/tillig/specification/node_modules/traverse/index.js:171:17
    at Array.forEach (<anonymous>)
```

Working backwards, I can see that things start happening [right around line 854](https://github.com/apideck-libraries/portman/blob/bba46b0d47a16d45bb3663886652bd7471c89cc4/src/application/Fuzzer.ts#L854) in [`Fuzzer.analyzeFuzzJsonSchema`](https://github.com/apideck-libraries/portman/blob/bba46b0d47a16d45bb3663886652bd7471c89cc4/src/application/Fuzzer.ts#L802) with the `required` issue happening specifically at [line 888](https://github.com/apideck-libraries/portman/blob/bba46b0d47a16d45bb3663886652bd7471c89cc4/src/application/Fuzzer.ts#L888).

I'm not entirely sure how to fix that yet, but it looks like there are similar sections in there for other reserved words like `minimum`, `maxiumum`, `maxLength`, `minLength`, and `nullable`.

**Comment by tillig** [comment]
Looks like a failing Jest test is something like:

```js
  it('should analyse JSON schema of request body with properties named after reserved words for fuzz detection', async () => {
    // Analyse JSON schema with properties that use reserved words
    const schema = {
      properties: {
        nullable: {
          type: 'object',
          properties: {
            required: {
              type: 'object',
              properties: {
                minimum: {
                  type: 'object',
                  required: ['maxLength'],
                  properties: {
                    maxLength: {
                      type: 'number',
                      example: 1,
                      minimum: 1,
                      maximum: 100,
                      minLength: 1,
                      maxLength: 5
                    }
                  }
                }
              }
            }
          }
        }
      }
    } as OpenAPIV3.SchemaObject

    const result = fuzzer.analyzeFuzzJsonSchema(schema)
    expect(result).toMatchSnapshot()
  })
```
